package com.keylesspalace.tusky.util;

// AUTOGENERATED
public class Emojis
{
    public static final String[][] EMOJIS = new String[][] {
{ //  # group: Smileys & Emotion
"😀", //  1F600 ; fully-qualified # 😀 grinning face 
"😃", //  1F603 ; fully-qualified # 😃 grinning face with big eyes 
"😄", //  1F604 ; fully-qualified # 😄 grinning face with smiling eyes 
"😁", //  1F601 ; fully-qualified # 😁 beaming face with smiling eyes 
"😆", //  1F606 ; fully-qualified # 😆 grinning squinting face 
"😅", //  1F605 ; fully-qualified # 😅 grinning face with sweat 
"🤣", //  1F923 ; fully-qualified # 🤣 rolling on the floor laughing 
"😂", //  1F602 ; fully-qualified # 😂 face with tears of joy 
"🙂", //  1F642 ; fully-qualified # 🙂 slightly smiling face 
"🙃", //  1F643 ; fully-qualified # 🙃 upside-down face 
"😉", //  1F609 ; fully-qualified # 😉 winking face 
"😊", //  1F60A ; fully-qualified # 😊 smiling face with smiling eyes 
"😇", //  1F607 ; fully-qualified # 😇 smiling face with halo 
"🥰", //  1F970 ; fully-qualified # 🥰 smiling face with hearts 
"😍", //  1F60D ; fully-qualified # 😍 smiling face with heart-eyes 
"🤩", //  1F929 ; fully-qualified # 🤩 star-struck 
"😘", //  1F618 ; fully-qualified # 😘 face blowing a kiss 
"😗", //  1F617 ; fully-qualified # 😗 kissing face 
"😚", //  1F61A ; fully-qualified # 😚 kissing face with closed eyes 
"😙", //  1F619 ; fully-qualified # 😙 kissing face with smiling eyes 
"😋", //  1F60B ; fully-qualified # 😋 face savoring food 
"😛", //  1F61B ; fully-qualified # 😛 face with tongue 
"😜", //  1F61C ; fully-qualified # 😜 winking face with tongue 
"🤪", //  1F92A ; fully-qualified # 🤪 zany face 
"😝", //  1F61D ; fully-qualified # 😝 squinting face with tongue 
"🤑", //  1F911 ; fully-qualified # 🤑 money-mouth face 
"🤗", //  1F917 ; fully-qualified # 🤗 hugging face 
"🤭", //  1F92D ; fully-qualified # 🤭 face with hand over mouth 
"🤫", //  1F92B ; fully-qualified # 🤫 shushing face 
"🤔", //  1F914 ; fully-qualified # 🤔 thinking face 
"🤐", //  1F910 ; fully-qualified # 🤐 zipper-mouth face 
"🤨", //  1F928 ; fully-qualified # 🤨 face with raised eyebrow 
"😐", //  1F610 ; fully-qualified # 😐 neutral face 
"😑", //  1F611 ; fully-qualified # 😑 expressionless face 
"😶", //  1F636 ; fully-qualified # 😶 face without mouth 
"😏", //  1F60F ; fully-qualified # 😏 smirking face 
"😒", //  1F612 ; fully-qualified # 😒 unamused face 
"🙄", //  1F644 ; fully-qualified # 🙄 face with rolling eyes 
"😬", //  1F62C ; fully-qualified # 😬 grimacing face 
"🤥", //  1F925 ; fully-qualified # 🤥 lying face 
"😌", //  1F60C ; fully-qualified # 😌 relieved face 
"😔", //  1F614 ; fully-qualified # 😔 pensive face 
"😪", //  1F62A ; fully-qualified # 😪 sleepy face 
"🤤", //  1F924 ; fully-qualified # 🤤 drooling face 
"😴", //  1F634 ; fully-qualified # 😴 sleeping face 
"😷", //  1F637 ; fully-qualified # 😷 face with medical mask 
"🤒", //  1F912 ; fully-qualified # 🤒 face with thermometer 
"🤕", //  1F915 ; fully-qualified # 🤕 face with head-bandage 
"🤢", //  1F922 ; fully-qualified # 🤢 nauseated face 
"🤮", //  1F92E ; fully-qualified # 🤮 face vomiting 
"🤧", //  1F927 ; fully-qualified # 🤧 sneezing face 
"🥵", //  1F975 ; fully-qualified # 🥵 hot face 
"🥶", //  1F976 ; fully-qualified # 🥶 cold face 
"🥴", //  1F974 ; fully-qualified # 🥴 woozy face 
"😵", //  1F635 ; fully-qualified # 😵 dizzy face 
"🤯", //  1F92F ; fully-qualified # 🤯 exploding head 
"🤠", //  1F920 ; fully-qualified # 🤠 cowboy hat face 
"🥳", //  1F973 ; fully-qualified # 🥳 partying face 
"😎", //  1F60E ; fully-qualified # 😎 smiling face with sunglasses 
"🤓", //  1F913 ; fully-qualified # 🤓 nerd face 
"🧐", //  1F9D0 ; fully-qualified # 🧐 face with monocle 
"😕", //  1F615 ; fully-qualified # 😕 confused face 
"😟", //  1F61F ; fully-qualified # 😟 worried face 
"🙁", //  1F641 ; fully-qualified # 🙁 slightly frowning face 
"😮", //  1F62E ; fully-qualified # 😮 face with open mouth 
"😯", //  1F62F ; fully-qualified # 😯 hushed face 
"😲", //  1F632 ; fully-qualified # 😲 astonished face 
"😳", //  1F633 ; fully-qualified # 😳 flushed face 
"🥺", //  1F97A ; fully-qualified # 🥺 pleading face 
"😦", //  1F626 ; fully-qualified # 😦 frowning face with open mouth 
"😧", //  1F627 ; fully-qualified # 😧 anguished face 
"😨", //  1F628 ; fully-qualified # 😨 fearful face 
"😰", //  1F630 ; fully-qualified # 😰 anxious face with sweat 
"😥", //  1F625 ; fully-qualified # 😥 sad but relieved face 
"😢", //  1F622 ; fully-qualified # 😢 crying face 
"😭", //  1F62D ; fully-qualified # 😭 loudly crying face 
"😱", //  1F631 ; fully-qualified # 😱 face screaming in fear 
"😖", //  1F616 ; fully-qualified # 😖 confounded face 
"😣", //  1F623 ; fully-qualified # 😣 persevering face 
"😞", //  1F61E ; fully-qualified # 😞 disappointed face 
"😓", //  1F613 ; fully-qualified # 😓 downcast face with sweat 
"😩", //  1F629 ; fully-qualified # 😩 weary face 
"😫", //  1F62B ; fully-qualified # 😫 tired face 
"🥱", //  1F971 ; fully-qualified # 🥱 yawning face 
"😤", //  1F624 ; fully-qualified # 😤 face with steam from nose 
"😡", //  1F621 ; fully-qualified # 😡 pouting face 
"😠", //  1F620 ; fully-qualified # 😠 angry face 
"🤬", //  1F92C ; fully-qualified # 🤬 face with symbols on mouth 
"😈", //  1F608 ; fully-qualified # 😈 smiling face with horns 
"👿", //  1F47F ; fully-qualified # 👿 angry face with horns 
"💀", //  1F480 ; fully-qualified # 💀 skull 
"💩", //  1F4A9 ; fully-qualified # 💩 pile of poo 
"🤡", //  1F921 ; fully-qualified # 🤡 clown face 
"👹", //  1F479 ; fully-qualified # 👹 ogre 
"👺", //  1F47A ; fully-qualified # 👺 goblin 
"👻", //  1F47B ; fully-qualified # 👻 ghost 
"👽", //  1F47D ; fully-qualified # 👽 alien 
"👾", //  1F47E ; fully-qualified # 👾 alien monster 
"🤖", //  1F916 ; fully-qualified # 🤖 robot 
"😺", //  1F63A ; fully-qualified # 😺 grinning cat 
"😸", //  1F638 ; fully-qualified # 😸 grinning cat with smiling eyes 
"😹", //  1F639 ; fully-qualified # 😹 cat with tears of joy 
"😻", //  1F63B ; fully-qualified # 😻 smiling cat with heart-eyes 
"😼", //  1F63C ; fully-qualified # 😼 cat with wry smile 
"😽", //  1F63D ; fully-qualified # 😽 kissing cat 
"🙀", //  1F640 ; fully-qualified # 🙀 weary cat 
"😿", //  1F63F ; fully-qualified # 😿 crying cat 
"😾", //  1F63E ; fully-qualified # 😾 pouting cat 
"🙈", //  1F648 ; fully-qualified # 🙈 see-no-evil monkey 
"🙉", //  1F649 ; fully-qualified # 🙉 hear-no-evil monkey 
"🙊", //  1F64A ; fully-qualified # 🙊 speak-no-evil monkey 
"💋", //  1F48B ; fully-qualified # 💋 kiss mark 
"💌", //  1F48C ; fully-qualified # 💌 love letter 
"💘", //  1F498 ; fully-qualified # 💘 heart with arrow 
"💝", //  1F49D ; fully-qualified # 💝 heart with ribbon 
"💖", //  1F496 ; fully-qualified # 💖 sparkling heart 
"💗", //  1F497 ; fully-qualified # 💗 growing heart 
"💓", //  1F493 ; fully-qualified # 💓 beating heart 
"💞", //  1F49E ; fully-qualified # 💞 revolving hearts 
"💕", //  1F495 ; fully-qualified # 💕 two hearts 
"💟", //  1F49F ; fully-qualified # 💟 heart decoration 
"💔", //  1F494 ; fully-qualified # 💔 broken heart 
"🧡", //  1F9E1 ; fully-qualified # 🧡 orange heart 
"💛", //  1F49B ; fully-qualified # 💛 yellow heart 
"💚", //  1F49A ; fully-qualified # 💚 green heart 
"💙", //  1F499 ; fully-qualified # 💙 blue heart 
"💜", //  1F49C ; fully-qualified # 💜 purple heart 
"🤎", //  1F90E ; fully-qualified # 🤎 brown heart 
"🖤", //  1F5A4 ; fully-qualified # 🖤 black heart 
"🤍", //  1F90D ; fully-qualified # 🤍 white heart 
"💯", //  1F4AF ; fully-qualified # 💯 hundred points 
"💢", //  1F4A2 ; fully-qualified # 💢 anger symbol 
"💥", //  1F4A5 ; fully-qualified # 💥 collision 
"💫", //  1F4AB ; fully-qualified # 💫 dizzy 
"💦", //  1F4A6 ; fully-qualified # 💦 sweat droplets 
"💨", //  1F4A8 ; fully-qualified # 💨 dashing away 
"💣", //  1F4A3 ; fully-qualified # 💣 bomb 
"💬", //  1F4AC ; fully-qualified # 💬 speech balloon 
"💭", //  1F4AD ; fully-qualified # 💭 thought balloon 
"💤", //  1F4A4 ; fully-qualified # 💤 zzz 
},
{ //  # group: People & Body
"👋", //  1F44B ; fully-qualified # 👋 waving hand 
"🤚", //  1F91A ; fully-qualified # 🤚 raised back of hand 
"✋", //  270B ; fully-qualified # ✋ raised hand 
"🖖", //  1F596 ; fully-qualified # 🖖 vulcan salute 
"👌", //  1F44C ; fully-qualified # 👌 OK hand 
"🤏", //  1F90F ; fully-qualified # 🤏 pinching hand 
"🤞", //  1F91E ; fully-qualified # 🤞 crossed fingers 
"🤟", //  1F91F ; fully-qualified # 🤟 love-you gesture 
"🤘", //  1F918 ; fully-qualified # 🤘 sign of the horns 
"🤙", //  1F919 ; fully-qualified # 🤙 call me hand 
"👈", //  1F448 ; fully-qualified # 👈 backhand index pointing left 
"👉", //  1F449 ; fully-qualified # 👉 backhand index pointing right 
"👆", //  1F446 ; fully-qualified # 👆 backhand index pointing up 
"🖕", //  1F595 ; fully-qualified # 🖕 middle finger 
"👇", //  1F447 ; fully-qualified # 👇 backhand index pointing down 
"👍", //  1F44D ; fully-qualified # 👍 thumbs up 
"👎", //  1F44E ; fully-qualified # 👎 thumbs down 
"✊", //  270A ; fully-qualified # ✊ raised fist 
"👊", //  1F44A ; fully-qualified # 👊 oncoming fist 
"🤛", //  1F91B ; fully-qualified # 🤛 left-facing fist 
"🤜", //  1F91C ; fully-qualified # 🤜 right-facing fist 
"👏", //  1F44F ; fully-qualified # 👏 clapping hands 
"🙌", //  1F64C ; fully-qualified # 🙌 raising hands 
"👐", //  1F450 ; fully-qualified # 👐 open hands 
"🤲", //  1F932 ; fully-qualified # 🤲 palms up together 
"🤝", //  1F91D ; fully-qualified # 🤝 handshake 
"🙏", //  1F64F ; fully-qualified # 🙏 folded hands 
"💅", //  1F485 ; fully-qualified # 💅 nail polish 
"🤳", //  1F933 ; fully-qualified # 🤳 selfie 
"💪", //  1F4AA ; fully-qualified # 💪 flexed biceps 
"🦾", //  1F9BE ; fully-qualified # 🦾 mechanical arm 
"🦿", //  1F9BF ; fully-qualified # 🦿 mechanical leg 
"🦵", //  1F9B5 ; fully-qualified # 🦵 leg 
"🦶", //  1F9B6 ; fully-qualified # 🦶 foot 
"👂", //  1F442 ; fully-qualified # 👂 ear 
"🦻", //  1F9BB ; fully-qualified # 🦻 ear with hearing aid 
"👃", //  1F443 ; fully-qualified # 👃 nose 
"🧠", //  1F9E0 ; fully-qualified # 🧠 brain 
"🦷", //  1F9B7 ; fully-qualified # 🦷 tooth 
"🦴", //  1F9B4 ; fully-qualified # 🦴 bone 
"👀", //  1F440 ; fully-qualified # 👀 eyes 
"👅", //  1F445 ; fully-qualified # 👅 tongue 
"👄", //  1F444 ; fully-qualified # 👄 mouth 
"👶", //  1F476 ; fully-qualified # 👶 baby 
"🧒", //  1F9D2 ; fully-qualified # 🧒 child 
"👦", //  1F466 ; fully-qualified # 👦 boy 
"👧", //  1F467 ; fully-qualified # 👧 girl 
"🧑", //  1F9D1 ; fully-qualified # 🧑 person 
"👱", //  1F471 ; fully-qualified # 👱 person: blond hair 
"👨", //  1F468 ; fully-qualified # 👨 man 
"🧔", //  1F9D4 ; fully-qualified # 🧔 man: beard 
"👩", //  1F469 ; fully-qualified # 👩 woman 
"🧓", //  1F9D3 ; fully-qualified # 🧓 older person 
"👴", //  1F474 ; fully-qualified # 👴 old man 
"👵", //  1F475 ; fully-qualified # 👵 old woman 
"🙍", //  1F64D ; fully-qualified # 🙍 person frowning 
"🙎", //  1F64E ; fully-qualified # 🙎 person pouting 
"🙅", //  1F645 ; fully-qualified # 🙅 person gesturing NO 
"🙆", //  1F646 ; fully-qualified # 🙆 person gesturing OK 
"💁", //  1F481 ; fully-qualified # 💁 person tipping hand 
"🙋", //  1F64B ; fully-qualified # 🙋 person raising hand 
"🧏", //  1F9CF ; fully-qualified # 🧏 deaf person 
"🙇", //  1F647 ; fully-qualified # 🙇 person bowing 
"🤦", //  1F926 ; fully-qualified # 🤦 person facepalming 
"🤷", //  1F937 ; fully-qualified # 🤷 person shrugging 
"👮", //  1F46E ; fully-qualified # 👮 police officer 
"💂", //  1F482 ; fully-qualified # 💂 guard 
"👷", //  1F477 ; fully-qualified # 👷 construction worker 
"🤴", //  1F934 ; fully-qualified # 🤴 prince 
"👸", //  1F478 ; fully-qualified # 👸 princess 
"👳", //  1F473 ; fully-qualified # 👳 person wearing turban 
"👲", //  1F472 ; fully-qualified # 👲 man with Chinese cap 
"🧕", //  1F9D5 ; fully-qualified # 🧕 woman with headscarf 
"🤵", //  1F935 ; fully-qualified # 🤵 man in tuxedo 
"👰", //  1F470 ; fully-qualified # 👰 bride with veil 
"🤰", //  1F930 ; fully-qualified # 🤰 pregnant woman 
"🤱", //  1F931 ; fully-qualified # 🤱 breast-feeding 
"👼", //  1F47C ; fully-qualified # 👼 baby angel 
"🎅", //  1F385 ; fully-qualified # 🎅 Santa Claus 
"🤶", //  1F936 ; fully-qualified # 🤶 Mrs. Claus 
"🦸", //  1F9B8 ; fully-qualified # 🦸 superhero 
"🦹", //  1F9B9 ; fully-qualified # 🦹 supervillain 
"🧙", //  1F9D9 ; fully-qualified # 🧙 mage 
"🧚", //  1F9DA ; fully-qualified # 🧚 fairy 
"🧛", //  1F9DB ; fully-qualified # 🧛 vampire 
"🧜", //  1F9DC ; fully-qualified # 🧜 merperson 
"🧝", //  1F9DD ; fully-qualified # 🧝 elf 
"🧞", //  1F9DE ; fully-qualified # 🧞 genie 
"🧟", //  1F9DF ; fully-qualified # 🧟 zombie 
"💆", //  1F486 ; fully-qualified # 💆 person getting massage 
"💇", //  1F487 ; fully-qualified # 💇 person getting haircut 
"🚶", //  1F6B6 ; fully-qualified # 🚶 person walking 
"🧍", //  1F9CD ; fully-qualified # 🧍 person standing 
"🧎", //  1F9CE ; fully-qualified # 🧎 person kneeling 
"🏃", //  1F3C3 ; fully-qualified # 🏃 person running 
"💃", //  1F483 ; fully-qualified # 💃 woman dancing 
"🕺", //  1F57A ; fully-qualified # 🕺 man dancing 
"👯", //  1F46F ; fully-qualified # 👯 people with bunny ears 
"🧖", //  1F9D6 ; fully-qualified # 🧖 person in steamy room 
"🧗", //  1F9D7 ; fully-qualified # 🧗 person climbing 
"🤺", //  1F93A ; fully-qualified # 🤺 person fencing 
"🏇", //  1F3C7 ; fully-qualified # 🏇 horse racing 
"🏂", //  1F3C2 ; fully-qualified # 🏂 snowboarder 
"🏄", //  1F3C4 ; fully-qualified # 🏄 person surfing 
"🚣", //  1F6A3 ; fully-qualified # 🚣 person rowing boat 
"🏊", //  1F3CA ; fully-qualified # 🏊 person swimming 
"🚴", //  1F6B4 ; fully-qualified # 🚴 person biking 
"🚵", //  1F6B5 ; fully-qualified # 🚵 person mountain biking 
"🤸", //  1F938 ; fully-qualified # 🤸 person cartwheeling 
"🤼", //  1F93C ; fully-qualified # 🤼 people wrestling 
"🤽", //  1F93D ; fully-qualified # 🤽 person playing water polo 
"🤾", //  1F93E ; fully-qualified # 🤾 person playing handball 
"🤹", //  1F939 ; fully-qualified # 🤹 person juggling 
"🧘", //  1F9D8 ; fully-qualified # 🧘 person in lotus position 
"🛀", //  1F6C0 ; fully-qualified # 🛀 person taking bath 
"🛌", //  1F6CC ; fully-qualified # 🛌 person in bed 
"👭", //  1F46D ; fully-qualified # 👭 women holding hands 
"👫", //  1F46B ; fully-qualified # 👫 woman and man holding hands 
"👬", //  1F46C ; fully-qualified # 👬 men holding hands 
"💏", //  1F48F ; fully-qualified # 💏 kiss 
"💑", //  1F491 ; fully-qualified # 💑 couple with heart 
"👪", //  1F46A ; fully-qualified # 👪 family 
"👤", //  1F464 ; fully-qualified # 👤 bust in silhouette 
"👥", //  1F465 ; fully-qualified # 👥 busts in silhouette 
"👣", //  1F463 ; fully-qualified # 👣 footprints 
},
{ //  # group: Animals & Nature
"🐵", //  1F435 ; fully-qualified # 🐵 monkey face 
"🐒", //  1F412 ; fully-qualified # 🐒 monkey 
"🦍", //  1F98D ; fully-qualified # 🦍 gorilla 
"🦧", //  1F9A7 ; fully-qualified # 🦧 orangutan 
"🐶", //  1F436 ; fully-qualified # 🐶 dog face 
"🐕", //  1F415 ; fully-qualified # 🐕 dog 
"🦮", //  1F9AE ; fully-qualified # 🦮 guide dog 
"🐩", //  1F429 ; fully-qualified # 🐩 poodle 
"🐺", //  1F43A ; fully-qualified # 🐺 wolf 
"🦊", //  1F98A ; fully-qualified # 🦊 fox 
"🦝", //  1F99D ; fully-qualified # 🦝 raccoon 
"🐱", //  1F431 ; fully-qualified # 🐱 cat face 
"🐈", //  1F408 ; fully-qualified # 🐈 cat 
"🦁", //  1F981 ; fully-qualified # 🦁 lion 
"🐯", //  1F42F ; fully-qualified # 🐯 tiger face 
"🐅", //  1F405 ; fully-qualified # 🐅 tiger 
"🐆", //  1F406 ; fully-qualified # 🐆 leopard 
"🐴", //  1F434 ; fully-qualified # 🐴 horse face 
"🐎", //  1F40E ; fully-qualified # 🐎 horse 
"🦄", //  1F984 ; fully-qualified # 🦄 unicorn 
"🦓", //  1F993 ; fully-qualified # 🦓 zebra 
"🦌", //  1F98C ; fully-qualified # 🦌 deer 
"🐮", //  1F42E ; fully-qualified # 🐮 cow face 
"🐂", //  1F402 ; fully-qualified # 🐂 ox 
"🐃", //  1F403 ; fully-qualified # 🐃 water buffalo 
"🐄", //  1F404 ; fully-qualified # 🐄 cow 
"🐷", //  1F437 ; fully-qualified # 🐷 pig face 
"🐖", //  1F416 ; fully-qualified # 🐖 pig 
"🐗", //  1F417 ; fully-qualified # 🐗 boar 
"🐽", //  1F43D ; fully-qualified # 🐽 pig nose 
"🐏", //  1F40F ; fully-qualified # 🐏 ram 
"🐑", //  1F411 ; fully-qualified # 🐑 ewe 
"🐐", //  1F410 ; fully-qualified # 🐐 goat 
"🐪", //  1F42A ; fully-qualified # 🐪 camel 
"🐫", //  1F42B ; fully-qualified # 🐫 two-hump camel 
"🦙", //  1F999 ; fully-qualified # 🦙 llama 
"🦒", //  1F992 ; fully-qualified # 🦒 giraffe 
"🐘", //  1F418 ; fully-qualified # 🐘 elephant 
"🦏", //  1F98F ; fully-qualified # 🦏 rhinoceros 
"🦛", //  1F99B ; fully-qualified # 🦛 hippopotamus 
"🐭", //  1F42D ; fully-qualified # 🐭 mouse face 
"🐁", //  1F401 ; fully-qualified # 🐁 mouse 
"🐀", //  1F400 ; fully-qualified # 🐀 rat 
"🐹", //  1F439 ; fully-qualified # 🐹 hamster 
"🐰", //  1F430 ; fully-qualified # 🐰 rabbit face 
"🐇", //  1F407 ; fully-qualified # 🐇 rabbit 
"🦔", //  1F994 ; fully-qualified # 🦔 hedgehog 
"🦇", //  1F987 ; fully-qualified # 🦇 bat 
"🐻", //  1F43B ; fully-qualified # 🐻 bear 
"🐨", //  1F428 ; fully-qualified # 🐨 koala 
"🐼", //  1F43C ; fully-qualified # 🐼 panda 
"🦥", //  1F9A5 ; fully-qualified # 🦥 sloth 
"🦦", //  1F9A6 ; fully-qualified # 🦦 otter 
"🦨", //  1F9A8 ; fully-qualified # 🦨 skunk 
"🦘", //  1F998 ; fully-qualified # 🦘 kangaroo 
"🦡", //  1F9A1 ; fully-qualified # 🦡 badger 
"🐾", //  1F43E ; fully-qualified # 🐾 paw prints 
"🦃", //  1F983 ; fully-qualified # 🦃 turkey 
"🐔", //  1F414 ; fully-qualified # 🐔 chicken 
"🐓", //  1F413 ; fully-qualified # 🐓 rooster 
"🐣", //  1F423 ; fully-qualified # 🐣 hatching chick 
"🐤", //  1F424 ; fully-qualified # 🐤 baby chick 
"🐥", //  1F425 ; fully-qualified # 🐥 front-facing baby chick 
"🐦", //  1F426 ; fully-qualified # 🐦 bird 
"🐧", //  1F427 ; fully-qualified # 🐧 penguin 
"🦅", //  1F985 ; fully-qualified # 🦅 eagle 
"🦆", //  1F986 ; fully-qualified # 🦆 duck 
"🦢", //  1F9A2 ; fully-qualified # 🦢 swan 
"🦉", //  1F989 ; fully-qualified # 🦉 owl 
"🦩", //  1F9A9 ; fully-qualified # 🦩 flamingo 
"🦚", //  1F99A ; fully-qualified # 🦚 peacock 
"🦜", //  1F99C ; fully-qualified # 🦜 parrot 
"🐸", //  1F438 ; fully-qualified # 🐸 frog 
"🐊", //  1F40A ; fully-qualified # 🐊 crocodile 
"🐢", //  1F422 ; fully-qualified # 🐢 turtle 
"🦎", //  1F98E ; fully-qualified # 🦎 lizard 
"🐍", //  1F40D ; fully-qualified # 🐍 snake 
"🐲", //  1F432 ; fully-qualified # 🐲 dragon face 
"🐉", //  1F409 ; fully-qualified # 🐉 dragon 
"🦕", //  1F995 ; fully-qualified # 🦕 sauropod 
"🦖", //  1F996 ; fully-qualified # 🦖 T-Rex 
"🐳", //  1F433 ; fully-qualified # 🐳 spouting whale 
"🐋", //  1F40B ; fully-qualified # 🐋 whale 
"🐬", //  1F42C ; fully-qualified # 🐬 dolphin 
"🐟", //  1F41F ; fully-qualified # 🐟 fish 
"🐠", //  1F420 ; fully-qualified # 🐠 tropical fish 
"🐡", //  1F421 ; fully-qualified # 🐡 blowfish 
"🦈", //  1F988 ; fully-qualified # 🦈 shark 
"🐙", //  1F419 ; fully-qualified # 🐙 octopus 
"🐚", //  1F41A ; fully-qualified # 🐚 spiral shell 
"🐌", //  1F40C ; fully-qualified # 🐌 snail 
"🦋", //  1F98B ; fully-qualified # 🦋 butterfly 
"🐛", //  1F41B ; fully-qualified # 🐛 bug 
"🐜", //  1F41C ; fully-qualified # 🐜 ant 
"🐝", //  1F41D ; fully-qualified # 🐝 honeybee 
"🐞", //  1F41E ; fully-qualified # 🐞 lady beetle 
"🦗", //  1F997 ; fully-qualified # 🦗 cricket 
"🦂", //  1F982 ; fully-qualified # 🦂 scorpion 
"🦟", //  1F99F ; fully-qualified # 🦟 mosquito 
"🦠", //  1F9A0 ; fully-qualified # 🦠 microbe 
"💐", //  1F490 ; fully-qualified # 💐 bouquet 
"🌸", //  1F338 ; fully-qualified # 🌸 cherry blossom 
"💮", //  1F4AE ; fully-qualified # 💮 white flower 
"🌹", //  1F339 ; fully-qualified # 🌹 rose 
"🥀", //  1F940 ; fully-qualified # 🥀 wilted flower 
"🌺", //  1F33A ; fully-qualified # 🌺 hibiscus 
"🌻", //  1F33B ; fully-qualified # 🌻 sunflower 
"🌼", //  1F33C ; fully-qualified # 🌼 blossom 
"🌷", //  1F337 ; fully-qualified # 🌷 tulip 
"🌱", //  1F331 ; fully-qualified # 🌱 seedling 
"🌲", //  1F332 ; fully-qualified # 🌲 evergreen tree 
"🌳", //  1F333 ; fully-qualified # 🌳 deciduous tree 
"🌴", //  1F334 ; fully-qualified # 🌴 palm tree 
"🌵", //  1F335 ; fully-qualified # 🌵 cactus 
"🌾", //  1F33E ; fully-qualified # 🌾 sheaf of rice 
"🌿", //  1F33F ; fully-qualified # 🌿 herb 
"🍀", //  1F340 ; fully-qualified # 🍀 four leaf clover 
"🍁", //  1F341 ; fully-qualified # 🍁 maple leaf 
"🍂", //  1F342 ; fully-qualified # 🍂 fallen leaf 
"🍃", //  1F343 ; fully-qualified # 🍃 leaf fluttering in wind 
},
{ //  # group: Food & Drink
"🍇", //  1F347 ; fully-qualified # 🍇 grapes 
"🍈", //  1F348 ; fully-qualified # 🍈 melon 
"🍉", //  1F349 ; fully-qualified # 🍉 watermelon 
"🍊", //  1F34A ; fully-qualified # 🍊 tangerine 
"🍋", //  1F34B ; fully-qualified # 🍋 lemon 
"🍌", //  1F34C ; fully-qualified # 🍌 banana 
"🍍", //  1F34D ; fully-qualified # 🍍 pineapple 
"🥭", //  1F96D ; fully-qualified # 🥭 mango 
"🍎", //  1F34E ; fully-qualified # 🍎 red apple 
"🍏", //  1F34F ; fully-qualified # 🍏 green apple 
"🍐", //  1F350 ; fully-qualified # 🍐 pear 
"🍑", //  1F351 ; fully-qualified # 🍑 peach 
"🍒", //  1F352 ; fully-qualified # 🍒 cherries 
"🍓", //  1F353 ; fully-qualified # 🍓 strawberry 
"🥝", //  1F95D ; fully-qualified # 🥝 kiwi fruit 
"🍅", //  1F345 ; fully-qualified # 🍅 tomato 
"🥥", //  1F965 ; fully-qualified # 🥥 coconut 
"🥑", //  1F951 ; fully-qualified # 🥑 avocado 
"🍆", //  1F346 ; fully-qualified # 🍆 eggplant 
"🥔", //  1F954 ; fully-qualified # 🥔 potato 
"🥕", //  1F955 ; fully-qualified # 🥕 carrot 
"🌽", //  1F33D ; fully-qualified # 🌽 ear of corn 
"🥒", //  1F952 ; fully-qualified # 🥒 cucumber 
"🥬", //  1F96C ; fully-qualified # 🥬 leafy green 
"🥦", //  1F966 ; fully-qualified # 🥦 broccoli 
"🧄", //  1F9C4 ; fully-qualified # 🧄 garlic 
"🧅", //  1F9C5 ; fully-qualified # 🧅 onion 
"🍄", //  1F344 ; fully-qualified # 🍄 mushroom 
"🥜", //  1F95C ; fully-qualified # 🥜 peanuts 
"🌰", //  1F330 ; fully-qualified # 🌰 chestnut 
"🍞", //  1F35E ; fully-qualified # 🍞 bread 
"🥐", //  1F950 ; fully-qualified # 🥐 croissant 
"🥖", //  1F956 ; fully-qualified # 🥖 baguette bread 
"🥨", //  1F968 ; fully-qualified # 🥨 pretzel 
"🥯", //  1F96F ; fully-qualified # 🥯 bagel 
"🥞", //  1F95E ; fully-qualified # 🥞 pancakes 
"🧇", //  1F9C7 ; fully-qualified # 🧇 waffle 
"🧀", //  1F9C0 ; fully-qualified # 🧀 cheese wedge 
"🍖", //  1F356 ; fully-qualified # 🍖 meat on bone 
"🍗", //  1F357 ; fully-qualified # 🍗 poultry leg 
"🥩", //  1F969 ; fully-qualified # 🥩 cut of meat 
"🥓", //  1F953 ; fully-qualified # 🥓 bacon 
"🍔", //  1F354 ; fully-qualified # 🍔 hamburger 
"🍟", //  1F35F ; fully-qualified # 🍟 french fries 
"🍕", //  1F355 ; fully-qualified # 🍕 pizza 
"🌭", //  1F32D ; fully-qualified # 🌭 hot dog 
"🥪", //  1F96A ; fully-qualified # 🥪 sandwich 
"🌮", //  1F32E ; fully-qualified # 🌮 taco 
"🌯", //  1F32F ; fully-qualified # 🌯 burrito 
"🥙", //  1F959 ; fully-qualified # 🥙 stuffed flatbread 
"🧆", //  1F9C6 ; fully-qualified # 🧆 falafel 
"🥚", //  1F95A ; fully-qualified # 🥚 egg 
"🍳", //  1F373 ; fully-qualified # 🍳 cooking 
"🥘", //  1F958 ; fully-qualified # 🥘 shallow pan of food 
"🍲", //  1F372 ; fully-qualified # 🍲 pot of food 
"🥣", //  1F963 ; fully-qualified # 🥣 bowl with spoon 
"🥗", //  1F957 ; fully-qualified # 🥗 green salad 
"🍿", //  1F37F ; fully-qualified # 🍿 popcorn 
"🧈", //  1F9C8 ; fully-qualified # 🧈 butter 
"🧂", //  1F9C2 ; fully-qualified # 🧂 salt 
"🥫", //  1F96B ; fully-qualified # 🥫 canned food 
"🍱", //  1F371 ; fully-qualified # 🍱 bento box 
"🍘", //  1F358 ; fully-qualified # 🍘 rice cracker 
"🍙", //  1F359 ; fully-qualified # 🍙 rice ball 
"🍚", //  1F35A ; fully-qualified # 🍚 cooked rice 
"🍛", //  1F35B ; fully-qualified # 🍛 curry rice 
"🍜", //  1F35C ; fully-qualified # 🍜 steaming bowl 
"🍝", //  1F35D ; fully-qualified # 🍝 spaghetti 
"🍠", //  1F360 ; fully-qualified # 🍠 roasted sweet potato 
"🍢", //  1F362 ; fully-qualified # 🍢 oden 
"🍣", //  1F363 ; fully-qualified # 🍣 sushi 
"🍤", //  1F364 ; fully-qualified # 🍤 fried shrimp 
"🍥", //  1F365 ; fully-qualified # 🍥 fish cake with swirl 
"🥮", //  1F96E ; fully-qualified # 🥮 moon cake 
"🍡", //  1F361 ; fully-qualified # 🍡 dango 
"🥟", //  1F95F ; fully-qualified # 🥟 dumpling 
"🥠", //  1F960 ; fully-qualified # 🥠 fortune cookie 
"🥡", //  1F961 ; fully-qualified # 🥡 takeout box 
"🦀", //  1F980 ; fully-qualified # 🦀 crab 
"🦞", //  1F99E ; fully-qualified # 🦞 lobster 
"🦐", //  1F990 ; fully-qualified # 🦐 shrimp 
"🦑", //  1F991 ; fully-qualified # 🦑 squid 
"🦪", //  1F9AA ; fully-qualified # 🦪 oyster 
"🍦", //  1F366 ; fully-qualified # 🍦 soft ice cream 
"🍧", //  1F367 ; fully-qualified # 🍧 shaved ice 
"🍨", //  1F368 ; fully-qualified # 🍨 ice cream 
"🍩", //  1F369 ; fully-qualified # 🍩 doughnut 
"🍪", //  1F36A ; fully-qualified # 🍪 cookie 
"🎂", //  1F382 ; fully-qualified # 🎂 birthday cake 
"🍰", //  1F370 ; fully-qualified # 🍰 shortcake 
"🧁", //  1F9C1 ; fully-qualified # 🧁 cupcake 
"🥧", //  1F967 ; fully-qualified # 🥧 pie 
"🍫", //  1F36B ; fully-qualified # 🍫 chocolate bar 
"🍬", //  1F36C ; fully-qualified # 🍬 candy 
"🍭", //  1F36D ; fully-qualified # 🍭 lollipop 
"🍮", //  1F36E ; fully-qualified # 🍮 custard 
"🍯", //  1F36F ; fully-qualified # 🍯 honey pot 
"🍼", //  1F37C ; fully-qualified # 🍼 baby bottle 
"🥛", //  1F95B ; fully-qualified # 🥛 glass of milk 
"☕", //  2615 ; fully-qualified # ☕ hot beverage 
"🍵", //  1F375 ; fully-qualified # 🍵 teacup without handle 
"🍶", //  1F376 ; fully-qualified # 🍶 sake 
"🍾", //  1F37E ; fully-qualified # 🍾 bottle with popping cork 
"🍷", //  1F377 ; fully-qualified # 🍷 wine glass 
"🍸", //  1F378 ; fully-qualified # 🍸 cocktail glass 
"🍹", //  1F379 ; fully-qualified # 🍹 tropical drink 
"🍺", //  1F37A ; fully-qualified # 🍺 beer mug 
"🍻", //  1F37B ; fully-qualified # 🍻 clinking beer mugs 
"🥂", //  1F942 ; fully-qualified # 🥂 clinking glasses 
"🥃", //  1F943 ; fully-qualified # 🥃 tumbler glass 
"🥤", //  1F964 ; fully-qualified # 🥤 cup with straw 
"🧃", //  1F9C3 ; fully-qualified # 🧃 beverage box 
"🧉", //  1F9C9 ; fully-qualified # 🧉 mate 
"🧊", //  1F9CA ; fully-qualified # 🧊 ice cube 
"🥢", //  1F962 ; fully-qualified # 🥢 chopsticks 
"🍴", //  1F374 ; fully-qualified # 🍴 fork and knife 
"🥄", //  1F944 ; fully-qualified # 🥄 spoon 
"🔪", //  1F52A ; fully-qualified # 🔪 kitchen knife 
"🏺", //  1F3FA ; fully-qualified # 🏺 amphora 
},
{ //  # group: Travel & Places
"🌍", //  1F30D ; fully-qualified # 🌍 globe showing Europe-Africa 
"🌎", //  1F30E ; fully-qualified # 🌎 globe showing Americas 
"🌏", //  1F30F ; fully-qualified # 🌏 globe showing Asia-Australia 
"🌐", //  1F310 ; fully-qualified # 🌐 globe with meridians 
"🗾", //  1F5FE ; fully-qualified # 🗾 map of Japan 
"🧭", //  1F9ED ; fully-qualified # 🧭 compass 
"🌋", //  1F30B ; fully-qualified # 🌋 volcano 
"🗻", //  1F5FB ; fully-qualified # 🗻 mount fuji 
"🧱", //  1F9F1 ; fully-qualified # 🧱 brick 
"🏠", //  1F3E0 ; fully-qualified # 🏠 house 
"🏡", //  1F3E1 ; fully-qualified # 🏡 house with garden 
"🏢", //  1F3E2 ; fully-qualified # 🏢 office building 
"🏣", //  1F3E3 ; fully-qualified # 🏣 Japanese post office 
"🏤", //  1F3E4 ; fully-qualified # 🏤 post office 
"🏥", //  1F3E5 ; fully-qualified # 🏥 hospital 
"🏦", //  1F3E6 ; fully-qualified # 🏦 bank 
"🏨", //  1F3E8 ; fully-qualified # 🏨 hotel 
"🏩", //  1F3E9 ; fully-qualified # 🏩 love hotel 
"🏪", //  1F3EA ; fully-qualified # 🏪 convenience store 
"🏫", //  1F3EB ; fully-qualified # 🏫 school 
"🏬", //  1F3EC ; fully-qualified # 🏬 department store 
"🏭", //  1F3ED ; fully-qualified # 🏭 factory 
"🏯", //  1F3EF ; fully-qualified # 🏯 Japanese castle 
"🏰", //  1F3F0 ; fully-qualified # 🏰 castle 
"💒", //  1F492 ; fully-qualified # 💒 wedding 
"🗼", //  1F5FC ; fully-qualified # 🗼 Tokyo tower 
"🗽", //  1F5FD ; fully-qualified # 🗽 Statue of Liberty 
"⛪", //  26EA ; fully-qualified # ⛪ church 
"🕌", //  1F54C ; fully-qualified # 🕌 mosque 
"🛕", //  1F6D5 ; fully-qualified # 🛕 hindu temple 
"🕍", //  1F54D ; fully-qualified # 🕍 synagogue 
"🕋", //  1F54B ; fully-qualified # 🕋 kaaba 
"⛲", //  26F2 ; fully-qualified # ⛲ fountain 
"⛺", //  26FA ; fully-qualified # ⛺ tent 
"🌁", //  1F301 ; fully-qualified # 🌁 foggy 
"🌃", //  1F303 ; fully-qualified # 🌃 night with stars 
"🌄", //  1F304 ; fully-qualified # 🌄 sunrise over mountains 
"🌅", //  1F305 ; fully-qualified # 🌅 sunrise 
"🌆", //  1F306 ; fully-qualified # 🌆 cityscape at dusk 
"🌇", //  1F307 ; fully-qualified # 🌇 sunset 
"🌉", //  1F309 ; fully-qualified # 🌉 bridge at night 
"🎠", //  1F3A0 ; fully-qualified # 🎠 carousel horse 
"🎡", //  1F3A1 ; fully-qualified # 🎡 ferris wheel 
"🎢", //  1F3A2 ; fully-qualified # 🎢 roller coaster 
"💈", //  1F488 ; fully-qualified # 💈 barber pole 
"🎪", //  1F3AA ; fully-qualified # 🎪 circus tent 
"🚂", //  1F682 ; fully-qualified # 🚂 locomotive 
"🚃", //  1F683 ; fully-qualified # 🚃 railway car 
"🚄", //  1F684 ; fully-qualified # 🚄 high-speed train 
"🚅", //  1F685 ; fully-qualified # 🚅 bullet train 
"🚆", //  1F686 ; fully-qualified # 🚆 train 
"🚇", //  1F687 ; fully-qualified # 🚇 metro 
"🚈", //  1F688 ; fully-qualified # 🚈 light rail 
"🚉", //  1F689 ; fully-qualified # 🚉 station 
"🚊", //  1F68A ; fully-qualified # 🚊 tram 
"🚝", //  1F69D ; fully-qualified # 🚝 monorail 
"🚞", //  1F69E ; fully-qualified # 🚞 mountain railway 
"🚋", //  1F68B ; fully-qualified # 🚋 tram car 
"🚌", //  1F68C ; fully-qualified # 🚌 bus 
"🚍", //  1F68D ; fully-qualified # 🚍 oncoming bus 
"🚎", //  1F68E ; fully-qualified # 🚎 trolleybus 
"🚐", //  1F690 ; fully-qualified # 🚐 minibus 
"🚑", //  1F691 ; fully-qualified # 🚑 ambulance 
"🚒", //  1F692 ; fully-qualified # 🚒 fire engine 
"🚓", //  1F693 ; fully-qualified # 🚓 police car 
"🚔", //  1F694 ; fully-qualified # 🚔 oncoming police car 
"🚕", //  1F695 ; fully-qualified # 🚕 taxi 
"🚖", //  1F696 ; fully-qualified # 🚖 oncoming taxi 
"🚗", //  1F697 ; fully-qualified # 🚗 automobile 
"🚘", //  1F698 ; fully-qualified # 🚘 oncoming automobile 
"🚙", //  1F699 ; fully-qualified # 🚙 sport utility vehicle 
"🚚", //  1F69A ; fully-qualified # 🚚 delivery truck 
"🚛", //  1F69B ; fully-qualified # 🚛 articulated lorry 
"🚜", //  1F69C ; fully-qualified # 🚜 tractor 
"🛵", //  1F6F5 ; fully-qualified # 🛵 motor scooter 
"🦽", //  1F9BD ; fully-qualified # 🦽 manual wheelchair 
"🦼", //  1F9BC ; fully-qualified # 🦼 motorized wheelchair 
"🛺", //  1F6FA ; fully-qualified # 🛺 auto rickshaw 
"🚲", //  1F6B2 ; fully-qualified # 🚲 bicycle 
"🛴", //  1F6F4 ; fully-qualified # 🛴 kick scooter 
"🛹", //  1F6F9 ; fully-qualified # 🛹 skateboard 
"🚏", //  1F68F ; fully-qualified # 🚏 bus stop 
"⛽", //  26FD ; fully-qualified # ⛽ fuel pump 
"🚨", //  1F6A8 ; fully-qualified # 🚨 police car light 
"🚥", //  1F6A5 ; fully-qualified # 🚥 horizontal traffic light 
"🚦", //  1F6A6 ; fully-qualified # 🚦 vertical traffic light 
"🛑", //  1F6D1 ; fully-qualified # 🛑 stop sign 
"🚧", //  1F6A7 ; fully-qualified # 🚧 construction 
"⚓", //  2693 ; fully-qualified # ⚓ anchor 
"⛵", //  26F5 ; fully-qualified # ⛵ sailboat 
"🛶", //  1F6F6 ; fully-qualified # 🛶 canoe 
"🚤", //  1F6A4 ; fully-qualified # 🚤 speedboat 
"🚢", //  1F6A2 ; fully-qualified # 🚢 ship 
"🛫", //  1F6EB ; fully-qualified # 🛫 airplane departure 
"🛬", //  1F6EC ; fully-qualified # 🛬 airplane arrival 
"🪂", //  1FA82 ; fully-qualified # 🪂 parachute 
"💺", //  1F4BA ; fully-qualified # 💺 seat 
"🚁", //  1F681 ; fully-qualified # 🚁 helicopter 
"🚟", //  1F69F ; fully-qualified # 🚟 suspension railway 
"🚠", //  1F6A0 ; fully-qualified # 🚠 mountain cableway 
"🚡", //  1F6A1 ; fully-qualified # 🚡 aerial tramway 
"🚀", //  1F680 ; fully-qualified # 🚀 rocket 
"🛸", //  1F6F8 ; fully-qualified # 🛸 flying saucer 
"🧳", //  1F9F3 ; fully-qualified # 🧳 luggage 
"⌛", //  231B ; fully-qualified # ⌛ hourglass done 
"⏳", //  23F3 ; fully-qualified # ⏳ hourglass not done 
"⌚", //  231A ; fully-qualified # ⌚ watch 
"⏰", //  23F0 ; fully-qualified # ⏰ alarm clock 
"🕛", //  1F55B ; fully-qualified # 🕛 twelve o’clock 
"🕧", //  1F567 ; fully-qualified # 🕧 twelve-thirty 
"🕐", //  1F550 ; fully-qualified # 🕐 one o’clock 
"🕜", //  1F55C ; fully-qualified # 🕜 one-thirty 
"🕑", //  1F551 ; fully-qualified # 🕑 two o’clock 
"🕝", //  1F55D ; fully-qualified # 🕝 two-thirty 
"🕒", //  1F552 ; fully-qualified # 🕒 three o’clock 
"🕞", //  1F55E ; fully-qualified # 🕞 three-thirty 
"🕓", //  1F553 ; fully-qualified # 🕓 four o’clock 
"🕟", //  1F55F ; fully-qualified # 🕟 four-thirty 
"🕔", //  1F554 ; fully-qualified # 🕔 five o’clock 
"🕠", //  1F560 ; fully-qualified # 🕠 five-thirty 
"🕕", //  1F555 ; fully-qualified # 🕕 six o’clock 
"🕡", //  1F561 ; fully-qualified # 🕡 six-thirty 
"🕖", //  1F556 ; fully-qualified # 🕖 seven o’clock 
"🕢", //  1F562 ; fully-qualified # 🕢 seven-thirty 
"🕗", //  1F557 ; fully-qualified # 🕗 eight o’clock 
"🕣", //  1F563 ; fully-qualified # 🕣 eight-thirty 
"🕘", //  1F558 ; fully-qualified # 🕘 nine o’clock 
"🕤", //  1F564 ; fully-qualified # 🕤 nine-thirty 
"🕙", //  1F559 ; fully-qualified # 🕙 ten o’clock 
"🕥", //  1F565 ; fully-qualified # 🕥 ten-thirty 
"🕚", //  1F55A ; fully-qualified # 🕚 eleven o’clock 
"🕦", //  1F566 ; fully-qualified # 🕦 eleven-thirty 
"🌑", //  1F311 ; fully-qualified # 🌑 new moon 
"🌒", //  1F312 ; fully-qualified # 🌒 waxing crescent moon 
"🌓", //  1F313 ; fully-qualified # 🌓 first quarter moon 
"🌔", //  1F314 ; fully-qualified # 🌔 waxing gibbous moon 
"🌕", //  1F315 ; fully-qualified # 🌕 full moon 
"🌖", //  1F316 ; fully-qualified # 🌖 waning gibbous moon 
"🌗", //  1F317 ; fully-qualified # 🌗 last quarter moon 
"🌘", //  1F318 ; fully-qualified # 🌘 waning crescent moon 
"🌙", //  1F319 ; fully-qualified # 🌙 crescent moon 
"🌚", //  1F31A ; fully-qualified # 🌚 new moon face 
"🌛", //  1F31B ; fully-qualified # 🌛 first quarter moon face 
"🌜", //  1F31C ; fully-qualified # 🌜 last quarter moon face 
"🌝", //  1F31D ; fully-qualified # 🌝 full moon face 
"🌞", //  1F31E ; fully-qualified # 🌞 sun with face 
"🪐", //  1FA90 ; fully-qualified # 🪐 ringed planet 
"⭐", //  2B50 ; fully-qualified # ⭐ star 
"🌟", //  1F31F ; fully-qualified # 🌟 glowing star 
"🌠", //  1F320 ; fully-qualified # 🌠 shooting star 
"🌌", //  1F30C ; fully-qualified # 🌌 milky way 
"⛅", //  26C5 ; fully-qualified # ⛅ sun behind cloud 
"🌀", //  1F300 ; fully-qualified # 🌀 cyclone 
"🌈", //  1F308 ; fully-qualified # 🌈 rainbow 
"🌂", //  1F302 ; fully-qualified # 🌂 closed umbrella 
"☔", //  2614 ; fully-qualified # ☔ umbrella with rain drops 
"⚡", //  26A1 ; fully-qualified # ⚡ high voltage 
"⛄", //  26C4 ; fully-qualified # ⛄ snowman without snow 
"🔥", //  1F525 ; fully-qualified # 🔥 fire 
"💧", //  1F4A7 ; fully-qualified # 💧 droplet 
"🌊", //  1F30A ; fully-qualified # 🌊 water wave 
},
{ //  # group: Activities
"🎃", //  1F383 ; fully-qualified # 🎃 jack-o-lantern 
"🎄", //  1F384 ; fully-qualified # 🎄 Christmas tree 
"🎆", //  1F386 ; fully-qualified # 🎆 fireworks 
"🎇", //  1F387 ; fully-qualified # 🎇 sparkler 
"🧨", //  1F9E8 ; fully-qualified # 🧨 firecracker 
"✨", //  2728 ; fully-qualified # ✨ sparkles 
"🎈", //  1F388 ; fully-qualified # 🎈 balloon 
"🎉", //  1F389 ; fully-qualified # 🎉 party popper 
"🎊", //  1F38A ; fully-qualified # 🎊 confetti ball 
"🎋", //  1F38B ; fully-qualified # 🎋 tanabata tree 
"🎍", //  1F38D ; fully-qualified # 🎍 pine decoration 
"🎎", //  1F38E ; fully-qualified # 🎎 Japanese dolls 
"🎏", //  1F38F ; fully-qualified # 🎏 carp streamer 
"🎐", //  1F390 ; fully-qualified # 🎐 wind chime 
"🎑", //  1F391 ; fully-qualified # 🎑 moon viewing ceremony 
"🧧", //  1F9E7 ; fully-qualified # 🧧 red envelope 
"🎀", //  1F380 ; fully-qualified # 🎀 ribbon 
"🎁", //  1F381 ; fully-qualified # 🎁 wrapped gift 
"🎫", //  1F3AB ; fully-qualified # 🎫 ticket 
"🏆", //  1F3C6 ; fully-qualified # 🏆 trophy 
"🏅", //  1F3C5 ; fully-qualified # 🏅 sports medal 
"🥇", //  1F947 ; fully-qualified # 🥇 1st place medal 
"🥈", //  1F948 ; fully-qualified # 🥈 2nd place medal 
"🥉", //  1F949 ; fully-qualified # 🥉 3rd place medal 
"⚽", //  26BD ; fully-qualified # ⚽ soccer ball 
"⚾", //  26BE ; fully-qualified # ⚾ baseball 
"🥎", //  1F94E ; fully-qualified # 🥎 softball 
"🏀", //  1F3C0 ; fully-qualified # 🏀 basketball 
"🏐", //  1F3D0 ; fully-qualified # 🏐 volleyball 
"🏈", //  1F3C8 ; fully-qualified # 🏈 american football 
"🏉", //  1F3C9 ; fully-qualified # 🏉 rugby football 
"🎾", //  1F3BE ; fully-qualified # 🎾 tennis 
"🥏", //  1F94F ; fully-qualified # 🥏 flying disc 
"🎳", //  1F3B3 ; fully-qualified # 🎳 bowling 
"🏏", //  1F3CF ; fully-qualified # 🏏 cricket game 
"🏑", //  1F3D1 ; fully-qualified # 🏑 field hockey 
"🏒", //  1F3D2 ; fully-qualified # 🏒 ice hockey 
"🥍", //  1F94D ; fully-qualified # 🥍 lacrosse 
"🏓", //  1F3D3 ; fully-qualified # 🏓 ping pong 
"🏸", //  1F3F8 ; fully-qualified # 🏸 badminton 
"🥊", //  1F94A ; fully-qualified # 🥊 boxing glove 
"🥋", //  1F94B ; fully-qualified # 🥋 martial arts uniform 
"🥅", //  1F945 ; fully-qualified # 🥅 goal net 
"⛳", //  26F3 ; fully-qualified # ⛳ flag in hole 
"🎣", //  1F3A3 ; fully-qualified # 🎣 fishing pole 
"🤿", //  1F93F ; fully-qualified # 🤿 diving mask 
"🎽", //  1F3BD ; fully-qualified # 🎽 running shirt 
"🎿", //  1F3BF ; fully-qualified # 🎿 skis 
"🛷", //  1F6F7 ; fully-qualified # 🛷 sled 
"🥌", //  1F94C ; fully-qualified # 🥌 curling stone 
"🎯", //  1F3AF ; fully-qualified # 🎯 direct hit 
"🪀", //  1FA80 ; fully-qualified # 🪀 yo-yo 
"🪁", //  1FA81 ; fully-qualified # 🪁 kite 
"🎱", //  1F3B1 ; fully-qualified # 🎱 pool 8 ball 
"🔮", //  1F52E ; fully-qualified # 🔮 crystal ball 
"🧿", //  1F9FF ; fully-qualified # 🧿 nazar amulet 
"🎮", //  1F3AE ; fully-qualified # 🎮 video game 
"🎰", //  1F3B0 ; fully-qualified # 🎰 slot machine 
"🎲", //  1F3B2 ; fully-qualified # 🎲 game die 
"🧩", //  1F9E9 ; fully-qualified # 🧩 puzzle piece 
"🧸", //  1F9F8 ; fully-qualified # 🧸 teddy bear 
"🃏", //  1F0CF ; fully-qualified # 🃏 joker 
"🀄", //  1F004 ; fully-qualified # 🀄 mahjong red dragon 
"🎴", //  1F3B4 ; fully-qualified # 🎴 flower playing cards 
"🎭", //  1F3AD ; fully-qualified # 🎭 performing arts 
"🎨", //  1F3A8 ; fully-qualified # 🎨 artist palette 
"🧵", //  1F9F5 ; fully-qualified # 🧵 thread 
"🧶", //  1F9F6 ; fully-qualified # 🧶 yarn 
},
{ //  # group: Objects
"👓", //  1F453 ; fully-qualified # 👓 glasses 
"🥽", //  1F97D ; fully-qualified # 🥽 goggles 
"🥼", //  1F97C ; fully-qualified # 🥼 lab coat 
"🦺", //  1F9BA ; fully-qualified # 🦺 safety vest 
"👔", //  1F454 ; fully-qualified # 👔 necktie 
"👕", //  1F455 ; fully-qualified # 👕 t-shirt 
"👖", //  1F456 ; fully-qualified # 👖 jeans 
"🧣", //  1F9E3 ; fully-qualified # 🧣 scarf 
"🧤", //  1F9E4 ; fully-qualified # 🧤 gloves 
"🧥", //  1F9E5 ; fully-qualified # 🧥 coat 
"🧦", //  1F9E6 ; fully-qualified # 🧦 socks 
"👗", //  1F457 ; fully-qualified # 👗 dress 
"👘", //  1F458 ; fully-qualified # 👘 kimono 
"🥻", //  1F97B ; fully-qualified # 🥻 sari 
"🩱", //  1FA71 ; fully-qualified # 🩱 one-piece swimsuit 
"🩲", //  1FA72 ; fully-qualified # 🩲 swim brief 
"🩳", //  1FA73 ; fully-qualified # 🩳 shorts 
"👙", //  1F459 ; fully-qualified # 👙 bikini 
"👚", //  1F45A ; fully-qualified # 👚 woman’s clothes 
"👛", //  1F45B ; fully-qualified # 👛 purse 
"👜", //  1F45C ; fully-qualified # 👜 handbag 
"👝", //  1F45D ; fully-qualified # 👝 clutch bag 
"🎒", //  1F392 ; fully-qualified # 🎒 backpack 
"👞", //  1F45E ; fully-qualified # 👞 man’s shoe 
"👟", //  1F45F ; fully-qualified # 👟 running shoe 
"🥾", //  1F97E ; fully-qualified # 🥾 hiking boot 
"🥿", //  1F97F ; fully-qualified # 🥿 flat shoe 
"👠", //  1F460 ; fully-qualified # 👠 high-heeled shoe 
"👡", //  1F461 ; fully-qualified # 👡 woman’s sandal 
"🩰", //  1FA70 ; fully-qualified # 🩰 ballet shoes 
"👢", //  1F462 ; fully-qualified # 👢 woman’s boot 
"👑", //  1F451 ; fully-qualified # 👑 crown 
"👒", //  1F452 ; fully-qualified # 👒 woman’s hat 
"🎩", //  1F3A9 ; fully-qualified # 🎩 top hat 
"🎓", //  1F393 ; fully-qualified # 🎓 graduation cap 
"🧢", //  1F9E2 ; fully-qualified # 🧢 billed cap 
"📿", //  1F4FF ; fully-qualified # 📿 prayer beads 
"💄", //  1F484 ; fully-qualified # 💄 lipstick 
"💍", //  1F48D ; fully-qualified # 💍 ring 
"💎", //  1F48E ; fully-qualified # 💎 gem stone 
"🔇", //  1F507 ; fully-qualified # 🔇 muted speaker 
"🔈", //  1F508 ; fully-qualified # 🔈 speaker low volume 
"🔉", //  1F509 ; fully-qualified # 🔉 speaker medium volume 
"🔊", //  1F50A ; fully-qualified # 🔊 speaker high volume 
"📢", //  1F4E2 ; fully-qualified # 📢 loudspeaker 
"📣", //  1F4E3 ; fully-qualified # 📣 megaphone 
"📯", //  1F4EF ; fully-qualified # 📯 postal horn 
"🔔", //  1F514 ; fully-qualified # 🔔 bell 
"🔕", //  1F515 ; fully-qualified # 🔕 bell with slash 
"🎼", //  1F3BC ; fully-qualified # 🎼 musical score 
"🎵", //  1F3B5 ; fully-qualified # 🎵 musical note 
"🎶", //  1F3B6 ; fully-qualified # 🎶 musical notes 
"🎤", //  1F3A4 ; fully-qualified # 🎤 microphone 
"🎧", //  1F3A7 ; fully-qualified # 🎧 headphone 
"📻", //  1F4FB ; fully-qualified # 📻 radio 
"🎷", //  1F3B7 ; fully-qualified # 🎷 saxophone 
"🎸", //  1F3B8 ; fully-qualified # 🎸 guitar 
"🎹", //  1F3B9 ; fully-qualified # 🎹 musical keyboard 
"🎺", //  1F3BA ; fully-qualified # 🎺 trumpet 
"🎻", //  1F3BB ; fully-qualified # 🎻 violin 
"🪕", //  1FA95 ; fully-qualified # 🪕 banjo 
"🥁", //  1F941 ; fully-qualified # 🥁 drum 
"📱", //  1F4F1 ; fully-qualified # 📱 mobile phone 
"📲", //  1F4F2 ; fully-qualified # 📲 mobile phone with arrow 
"📞", //  1F4DE ; fully-qualified # 📞 telephone receiver 
"📟", //  1F4DF ; fully-qualified # 📟 pager 
"📠", //  1F4E0 ; fully-qualified # 📠 fax machine 
"🔋", //  1F50B ; fully-qualified # 🔋 battery 
"🔌", //  1F50C ; fully-qualified # 🔌 electric plug 
"💻", //  1F4BB ; fully-qualified # 💻 laptop computer 
"💽", //  1F4BD ; fully-qualified # 💽 computer disk 
"💾", //  1F4BE ; fully-qualified # 💾 floppy disk 
"💿", //  1F4BF ; fully-qualified # 💿 optical disk 
"📀", //  1F4C0 ; fully-qualified # 📀 dvd 
"🧮", //  1F9EE ; fully-qualified # 🧮 abacus 
"🎥", //  1F3A5 ; fully-qualified # 🎥 movie camera 
"🎬", //  1F3AC ; fully-qualified # 🎬 clapper board 
"📺", //  1F4FA ; fully-qualified # 📺 television 
"📷", //  1F4F7 ; fully-qualified # 📷 camera 
"📸", //  1F4F8 ; fully-qualified # 📸 camera with flash 
"📹", //  1F4F9 ; fully-qualified # 📹 video camera 
"📼", //  1F4FC ; fully-qualified # 📼 videocassette 
"🔍", //  1F50D ; fully-qualified # 🔍 magnifying glass tilted left 
"🔎", //  1F50E ; fully-qualified # 🔎 magnifying glass tilted right 
"💡", //  1F4A1 ; fully-qualified # 💡 light bulb 
"🔦", //  1F526 ; fully-qualified # 🔦 flashlight 
"🏮", //  1F3EE ; fully-qualified # 🏮 red paper lantern 
"🪔", //  1FA94 ; fully-qualified # 🪔 diya lamp 
"📔", //  1F4D4 ; fully-qualified # 📔 notebook with decorative cover 
"📕", //  1F4D5 ; fully-qualified # 📕 closed book 
"📖", //  1F4D6 ; fully-qualified # 📖 open book 
"📗", //  1F4D7 ; fully-qualified # 📗 green book 
"📘", //  1F4D8 ; fully-qualified # 📘 blue book 
"📙", //  1F4D9 ; fully-qualified # 📙 orange book 
"📚", //  1F4DA ; fully-qualified # 📚 books 
"📓", //  1F4D3 ; fully-qualified # 📓 notebook 
"📒", //  1F4D2 ; fully-qualified # 📒 ledger 
"📃", //  1F4C3 ; fully-qualified # 📃 page with curl 
"📜", //  1F4DC ; fully-qualified # 📜 scroll 
"📄", //  1F4C4 ; fully-qualified # 📄 page facing up 
"📰", //  1F4F0 ; fully-qualified # 📰 newspaper 
"📑", //  1F4D1 ; fully-qualified # 📑 bookmark tabs 
"🔖", //  1F516 ; fully-qualified # 🔖 bookmark 
"💰", //  1F4B0 ; fully-qualified # 💰 money bag 
"💴", //  1F4B4 ; fully-qualified # 💴 yen banknote 
"💵", //  1F4B5 ; fully-qualified # 💵 dollar banknote 
"💶", //  1F4B6 ; fully-qualified # 💶 euro banknote 
"💷", //  1F4B7 ; fully-qualified # 💷 pound banknote 
"💸", //  1F4B8 ; fully-qualified # 💸 money with wings 
"💳", //  1F4B3 ; fully-qualified # 💳 credit card 
"🧾", //  1F9FE ; fully-qualified # 🧾 receipt 
"💹", //  1F4B9 ; fully-qualified # 💹 chart increasing with yen 
"💱", //  1F4B1 ; fully-qualified # 💱 currency exchange 
"💲", //  1F4B2 ; fully-qualified # 💲 heavy dollar sign 
"📧", //  1F4E7 ; fully-qualified # 📧 e-mail 
"📨", //  1F4E8 ; fully-qualified # 📨 incoming envelope 
"📩", //  1F4E9 ; fully-qualified # 📩 envelope with arrow 
"📤", //  1F4E4 ; fully-qualified # 📤 outbox tray 
"📥", //  1F4E5 ; fully-qualified # 📥 inbox tray 
"📦", //  1F4E6 ; fully-qualified # 📦 package 
"📫", //  1F4EB ; fully-qualified # 📫 closed mailbox with raised flag 
"📪", //  1F4EA ; fully-qualified # 📪 closed mailbox with lowered flag 
"📬", //  1F4EC ; fully-qualified # 📬 open mailbox with raised flag 
"📭", //  1F4ED ; fully-qualified # 📭 open mailbox with lowered flag 
"📮", //  1F4EE ; fully-qualified # 📮 postbox 
"📝", //  1F4DD ; fully-qualified # 📝 memo 
"💼", //  1F4BC ; fully-qualified # 💼 briefcase 
"📁", //  1F4C1 ; fully-qualified # 📁 file folder 
"📂", //  1F4C2 ; fully-qualified # 📂 open file folder 
"📅", //  1F4C5 ; fully-qualified # 📅 calendar 
"📆", //  1F4C6 ; fully-qualified # 📆 tear-off calendar 
"📇", //  1F4C7 ; fully-qualified # 📇 card index 
"📈", //  1F4C8 ; fully-qualified # 📈 chart increasing 
"📉", //  1F4C9 ; fully-qualified # 📉 chart decreasing 
"📊", //  1F4CA ; fully-qualified # 📊 bar chart 
"📋", //  1F4CB ; fully-qualified # 📋 clipboard 
"📌", //  1F4CC ; fully-qualified # 📌 pushpin 
"📍", //  1F4CD ; fully-qualified # 📍 round pushpin 
"📎", //  1F4CE ; fully-qualified # 📎 paperclip 
"📏", //  1F4CF ; fully-qualified # 📏 straight ruler 
"📐", //  1F4D0 ; fully-qualified # 📐 triangular ruler 
"🔒", //  1F512 ; fully-qualified # 🔒 locked 
"🔓", //  1F513 ; fully-qualified # 🔓 unlocked 
"🔏", //  1F50F ; fully-qualified # 🔏 locked with pen 
"🔐", //  1F510 ; fully-qualified # 🔐 locked with key 
"🔑", //  1F511 ; fully-qualified # 🔑 key 
"🔨", //  1F528 ; fully-qualified # 🔨 hammer 
"🪓", //  1FA93 ; fully-qualified # 🪓 axe 
"🔫", //  1F52B ; fully-qualified # 🔫 pistol 
"🏹", //  1F3F9 ; fully-qualified # 🏹 bow and arrow 
"🔧", //  1F527 ; fully-qualified # 🔧 wrench 
"🔩", //  1F529 ; fully-qualified # 🔩 nut and bolt 
"🦯", //  1F9AF ; fully-qualified # 🦯 probing cane 
"🔗", //  1F517 ; fully-qualified # 🔗 link 
"🧰", //  1F9F0 ; fully-qualified # 🧰 toolbox 
"🧲", //  1F9F2 ; fully-qualified # 🧲 magnet 
"🧪", //  1F9EA ; fully-qualified # 🧪 test tube 
"🧫", //  1F9EB ; fully-qualified # 🧫 petri dish 
"🧬", //  1F9EC ; fully-qualified # 🧬 dna 
"🔬", //  1F52C ; fully-qualified # 🔬 microscope 
"🔭", //  1F52D ; fully-qualified # 🔭 telescope 
"📡", //  1F4E1 ; fully-qualified # 📡 satellite antenna 
"💉", //  1F489 ; fully-qualified # 💉 syringe 
"🩸", //  1FA78 ; fully-qualified # 🩸 drop of blood 
"💊", //  1F48A ; fully-qualified # 💊 pill 
"🩹", //  1FA79 ; fully-qualified # 🩹 adhesive bandage 
"🩺", //  1FA7A ; fully-qualified # 🩺 stethoscope 
"🚪", //  1F6AA ; fully-qualified # 🚪 door 
"🪑", //  1FA91 ; fully-qualified # 🪑 chair 
"🚽", //  1F6BD ; fully-qualified # 🚽 toilet 
"🚿", //  1F6BF ; fully-qualified # 🚿 shower 
"🛁", //  1F6C1 ; fully-qualified # 🛁 bathtub 
"🪒", //  1FA92 ; fully-qualified # 🪒 razor 
"🧴", //  1F9F4 ; fully-qualified # 🧴 lotion bottle 
"🧷", //  1F9F7 ; fully-qualified # 🧷 safety pin 
"🧹", //  1F9F9 ; fully-qualified # 🧹 broom 
"🧺", //  1F9FA ; fully-qualified # 🧺 basket 
"🧻", //  1F9FB ; fully-qualified # 🧻 roll of paper 
"🧼", //  1F9FC ; fully-qualified # 🧼 soap 
"🧽", //  1F9FD ; fully-qualified # 🧽 sponge 
"🧯", //  1F9EF ; fully-qualified # 🧯 fire extinguisher 
"🛒", //  1F6D2 ; fully-qualified # 🛒 shopping cart 
"🚬", //  1F6AC ; fully-qualified # 🚬 cigarette 
"🗿", //  1F5FF ; fully-qualified # 🗿 moai 
},
{ //  # group: Symbols
"🏧", //  1F3E7 ; fully-qualified # 🏧 ATM sign 
"🚮", //  1F6AE ; fully-qualified # 🚮 litter in bin sign 
"🚰", //  1F6B0 ; fully-qualified # 🚰 potable water 
"♿", //  267F ; fully-qualified # ♿ wheelchair symbol 
"🚹", //  1F6B9 ; fully-qualified # 🚹 men’s room 
"🚺", //  1F6BA ; fully-qualified # 🚺 women’s room 
"🚻", //  1F6BB ; fully-qualified # 🚻 restroom 
"🚼", //  1F6BC ; fully-qualified # 🚼 baby symbol 
"🚾", //  1F6BE ; fully-qualified # 🚾 water closet 
"🛂", //  1F6C2 ; fully-qualified # 🛂 passport control 
"🛃", //  1F6C3 ; fully-qualified # 🛃 customs 
"🛄", //  1F6C4 ; fully-qualified # 🛄 baggage claim 
"🛅", //  1F6C5 ; fully-qualified # 🛅 left luggage 
"🚸", //  1F6B8 ; fully-qualified # 🚸 children crossing 
"⛔", //  26D4 ; fully-qualified # ⛔ no entry 
"🚫", //  1F6AB ; fully-qualified # 🚫 prohibited 
"🚳", //  1F6B3 ; fully-qualified # 🚳 no bicycles 
"🚭", //  1F6AD ; fully-qualified # 🚭 no smoking 
"🚯", //  1F6AF ; fully-qualified # 🚯 no littering 
"🚱", //  1F6B1 ; fully-qualified # 🚱 non-potable water 
"🚷", //  1F6B7 ; fully-qualified # 🚷 no pedestrians 
"📵", //  1F4F5 ; fully-qualified # 📵 no mobile phones 
"🔞", //  1F51E ; fully-qualified # 🔞 no one under eighteen 
"🔃", //  1F503 ; fully-qualified # 🔃 clockwise vertical arrows 
"🔄", //  1F504 ; fully-qualified # 🔄 counterclockwise arrows button 
"🔙", //  1F519 ; fully-qualified # 🔙 BACK arrow 
"🔚", //  1F51A ; fully-qualified # 🔚 END arrow 
"🔛", //  1F51B ; fully-qualified # 🔛 ON! arrow 
"🔜", //  1F51C ; fully-qualified # 🔜 SOON arrow 
"🔝", //  1F51D ; fully-qualified # 🔝 TOP arrow 
"🛐", //  1F6D0 ; fully-qualified # 🛐 place of worship 
"🕎", //  1F54E ; fully-qualified # 🕎 menorah 
"🔯", //  1F52F ; fully-qualified # 🔯 dotted six-pointed star 
"♈", //  2648 ; fully-qualified # ♈ Aries 
"♉", //  2649 ; fully-qualified # ♉ Taurus 
"♊", //  264A ; fully-qualified # ♊ Gemini 
"♋", //  264B ; fully-qualified # ♋ Cancer 
"♌", //  264C ; fully-qualified # ♌ Leo 
"♍", //  264D ; fully-qualified # ♍ Virgo 
"♎", //  264E ; fully-qualified # ♎ Libra 
"♏", //  264F ; fully-qualified # ♏ Scorpio 
"♐", //  2650 ; fully-qualified # ♐ Sagittarius 
"♑", //  2651 ; fully-qualified # ♑ Capricorn 
"♒", //  2652 ; fully-qualified # ♒ Aquarius 
"♓", //  2653 ; fully-qualified # ♓ Pisces 
"⛎", //  26CE ; fully-qualified # ⛎ Ophiuchus 
"🔀", //  1F500 ; fully-qualified # 🔀 shuffle tracks button 
"🔁", //  1F501 ; fully-qualified # 🔁 repeat button 
"🔂", //  1F502 ; fully-qualified # 🔂 repeat single button 
"⏩", //  23E9 ; fully-qualified # ⏩ fast-forward button 
"⏪", //  23EA ; fully-qualified # ⏪ fast reverse button 
"🔼", //  1F53C ; fully-qualified # 🔼 upwards button 
"⏫", //  23EB ; fully-qualified # ⏫ fast up button 
"🔽", //  1F53D ; fully-qualified # 🔽 downwards button 
"⏬", //  23EC ; fully-qualified # ⏬ fast down button 
"🎦", //  1F3A6 ; fully-qualified # 🎦 cinema 
"🔅", //  1F505 ; fully-qualified # 🔅 dim button 
"🔆", //  1F506 ; fully-qualified # 🔆 bright button 
"📶", //  1F4F6 ; fully-qualified # 📶 antenna bars 
"📳", //  1F4F3 ; fully-qualified # 📳 vibration mode 
"📴", //  1F4F4 ; fully-qualified # 📴 mobile phone off 
"🔱", //  1F531 ; fully-qualified # 🔱 trident emblem 
"📛", //  1F4DB ; fully-qualified # 📛 name badge 
"🔰", //  1F530 ; fully-qualified # 🔰 Japanese symbol for beginner 
"⭕", //  2B55 ; fully-qualified # ⭕ hollow red circle 
"✅", //  2705 ; fully-qualified # ✅ check mark button 
"❌", //  274C ; fully-qualified # ❌ cross mark 
"❎", //  274E ; fully-qualified # ❎ cross mark button 
"➕", //  2795 ; fully-qualified # ➕ plus sign 
"➖", //  2796 ; fully-qualified # ➖ minus sign 
"➗", //  2797 ; fully-qualified # ➗ division sign 
"➰", //  27B0 ; fully-qualified # ➰ curly loop 
"➿", //  27BF ; fully-qualified # ➿ double curly loop 
"❓", //  2753 ; fully-qualified # ❓ question mark 
"❔", //  2754 ; fully-qualified # ❔ white question mark 
"❕", //  2755 ; fully-qualified # ❕ white exclamation mark 
"❗", //  2757 ; fully-qualified # ❗ exclamation mark 
"🔟", //  1F51F ; fully-qualified # 🔟 keycap: 10 
"🔠", //  1F520 ; fully-qualified # 🔠 input latin uppercase 
"🔡", //  1F521 ; fully-qualified # 🔡 input latin lowercase 
"🔢", //  1F522 ; fully-qualified # 🔢 input numbers 
"🔣", //  1F523 ; fully-qualified # 🔣 input symbols 
"🔤", //  1F524 ; fully-qualified # 🔤 input latin letters 
"🆎", //  1F18E ; fully-qualified # 🆎 AB button (blood type) 
"🆑", //  1F191 ; fully-qualified # 🆑 CL button 
"🆒", //  1F192 ; fully-qualified # 🆒 COOL button 
"🆓", //  1F193 ; fully-qualified # 🆓 FREE button 
"🆔", //  1F194 ; fully-qualified # 🆔 ID button 
"🆕", //  1F195 ; fully-qualified # 🆕 NEW button 
"🆖", //  1F196 ; fully-qualified # 🆖 NG button 
"🆗", //  1F197 ; fully-qualified # 🆗 OK button 
"🆘", //  1F198 ; fully-qualified # 🆘 SOS button 
"🆙", //  1F199 ; fully-qualified # 🆙 UP! button 
"🆚", //  1F19A ; fully-qualified # 🆚 VS button 
"🈁", //  1F201 ; fully-qualified # 🈁 Japanese “here” button 
"🈶", //  1F236 ; fully-qualified # 🈶 Japanese “not free of charge” button 
"🈯", //  1F22F ; fully-qualified # 🈯 Japanese “reserved” button 
"🉐", //  1F250 ; fully-qualified # 🉐 Japanese “bargain” button 
"🈹", //  1F239 ; fully-qualified # 🈹 Japanese “discount” button 
"🈚", //  1F21A ; fully-qualified # 🈚 Japanese “free of charge” button 
"🈲", //  1F232 ; fully-qualified # 🈲 Japanese “prohibited” button 
"🉑", //  1F251 ; fully-qualified # 🉑 Japanese “acceptable” button 
"🈸", //  1F238 ; fully-qualified # 🈸 Japanese “application” button 
"🈴", //  1F234 ; fully-qualified # 🈴 Japanese “passing grade” button 
"🈳", //  1F233 ; fully-qualified # 🈳 Japanese “vacancy” button 
"🈺", //  1F23A ; fully-qualified # 🈺 Japanese “open for business” button 
"🈵", //  1F235 ; fully-qualified # 🈵 Japanese “no vacancy” button 
"🔴", //  1F534 ; fully-qualified # 🔴 red circle 
"🟠", //  1F7E0 ; fully-qualified # 🟠 orange circle 
"🟡", //  1F7E1 ; fully-qualified # 🟡 yellow circle 
"🟢", //  1F7E2 ; fully-qualified # 🟢 green circle 
"🔵", //  1F535 ; fully-qualified # 🔵 blue circle 
"🟣", //  1F7E3 ; fully-qualified # 🟣 purple circle 
"🟤", //  1F7E4 ; fully-qualified # 🟤 brown circle 
"⚫", //  26AB ; fully-qualified # ⚫ black circle 
"⚪", //  26AA ; fully-qualified # ⚪ white circle 
"🟥", //  1F7E5 ; fully-qualified # 🟥 red square 
"🟧", //  1F7E7 ; fully-qualified # 🟧 orange square 
"🟨", //  1F7E8 ; fully-qualified # 🟨 yellow square 
"🟩", //  1F7E9 ; fully-qualified # 🟩 green square 
"🟦", //  1F7E6 ; fully-qualified # 🟦 blue square 
"🟪", //  1F7EA ; fully-qualified # 🟪 purple square 
"🟫", //  1F7EB ; fully-qualified # 🟫 brown square 
"⬛", //  2B1B ; fully-qualified # ⬛ black large square 
"⬜", //  2B1C ; fully-qualified # ⬜ white large square 
"◾", //  25FE ; fully-qualified # ◾ black medium-small square 
"◽", //  25FD ; fully-qualified # ◽ white medium-small square 
"🔶", //  1F536 ; fully-qualified # 🔶 large orange diamond 
"🔷", //  1F537 ; fully-qualified # 🔷 large blue diamond 
"🔸", //  1F538 ; fully-qualified # 🔸 small orange diamond 
"🔹", //  1F539 ; fully-qualified # 🔹 small blue diamond 
"🔺", //  1F53A ; fully-qualified # 🔺 red triangle pointed up 
"🔻", //  1F53B ; fully-qualified # 🔻 red triangle pointed down 
"💠", //  1F4A0 ; fully-qualified # 💠 diamond with a dot 
"🔘", //  1F518 ; fully-qualified # 🔘 radio button 
"🔳", //  1F533 ; fully-qualified # 🔳 white square button 
"🔲", //  1F532 ; fully-qualified # 🔲 black square button 
},
{ //  # group: Flags
"🏁", //  1F3C1 ; fully-qualified # 🏁 chequered flag 
"🚩", //  1F6A9 ; fully-qualified # 🚩 triangular flag 
"🎌", //  1F38C ; fully-qualified # 🎌 crossed flags 
"🏴", //  1F3F4 ; fully-qualified # 🏴 black flag 
}
	};
}
