name: Check style

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-style:
    name: Ktlint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Setup Java
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Gradle Setup
      - uses: gradle/actions/setup-gradle@v3

      - name: Run ktlint
        run: |
          cd husky
          ./gradlew ktlintCheck
