name: Run tests

permissions:
  contents: read

on:
  workflow_run:
    workflows: [Check style]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          cd husky
          ./gradlew testHuskyStableReleaseUnitTest
