on:
  pull_request:

permissions:
  contents: read

jobs:
  run-tests:
    needs: [check-style]
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          cd husky
          ./gradlew testHuskyStableReleaseUnitTest
